ProyectoDiarsProgramacionDeObras/ProyectoDiarsProgramacionDeObras/Controllers/ObraController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CapaEntidad;
using CapaLogica;

namespace ProyectoDiarsProgramacionDeObras.Controllers
{
    public class ObraController : Controller
    {
        [HttpGet]
        public ActionResult ListaObra()
        {
            List<entObra> lista = logObra.Instancia.ListarObra();

            foreach (entObra obra in lista)
            {
                if (logPrograma.Instancia.ObtenerPrograma(obra.ObraID).Obra==null)
                {
                    logPrograma.Instancia.InsertaPrograma(new entPrograma { Obra = obra, Residente = logResidente.Instancia.ObtenerResidente(1) });
                }
            }

            ViewBag.lista = lista;
            return View(lista);
        }

        [HttpGet]
        public ActionResult NuevaObra()
        {
            return View();
        }

        [HttpPost]
        public ActionResult NuevaObra(entObra obra)
        {
            try
            {
                Boolean inserta = logObra.Instancia.InsertaObra(obra);
                if (inserta)
                {
                    return RedirectToAction("ListaObra");
                }
                else
                {
                    return View(obra);
                }
            }
            catch (ApplicationException ex)
            {
                return RedirectToAction("ListaObra", new { msjException = ex.Message });
            }

        }

        [HttpGet]
        public ActionResult EditaObra(int ObraID)
        {
            entObra obra = logObra.Instancia.ObtenerObra(ObraID);
            if (obra == null)
            {
                return HttpNotFound();
            }
            return View(obra);
        }

        [HttpPost]
        public ActionResult EditaObra(entObra obra)
        {
            try
            {
                Boolean edita = logObra.Instancia.EditaObra(obra);
                if (edita)
                {
                    return RedirectToAction("ListaObra");
                }
                else
                {
                    return View(obra);
                }
            }
            catch (ApplicationException ex)
            {
                return RedirectToAction("ListaObra", new { msjException = ex.Message });
            }
        }

        [HttpGet]
        public ActionResult EliminaObra(int ObraID)
        {
            try
            {
                Boolean edita = logObra.Instancia.EliminaObra(ObraID);
                return RedirectToAction("ListaObra");
            }
            catch (ApplicationException ex)
            {
                return RedirectToAction("ListaObra", new { msjException = ex.Message });
            }
        }
    }   
}

ProyectoDiarsProgramacionDeObras/ProyectoDiarsProgramacionDeObras/Controllers/ProgramaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CapaEntidad;
using CapaLogica;

namespace ProyectoDiarsProgramacionDeObras.Controllers
{
    public class ProgramaController : Controller
    {
        [HttpGet]
        public ActionResult ListaPrograma()
        {
            List<entPrograma> lista = logPrograma.Instancia.ListarPrograma();
            ViewBag.lista = lista;
            return View(lista);
        }

        [HttpGet]
        public ActionResult SeleccionaObra(int ProgramaID)
        {
            try
            {
                return RedirectToAction("ListaActividad", "Actividad", new { ProgramaID = ProgramaID });
            }
            catch (ApplicationException ex)
            {
                return RedirectToAction("ListaPrograma", new { msjException = ex.Message });
            }
        }
    }
}

ProyectoDiarsProgramacionDeObras/ProyectoDiarsProgramacionDeObras/Controllers/TareaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CapaEntidad;
using CapaLogica;

namespace ProyectoDiarsProgramacionDeObras.Controllers
{
    public class TareaController : Controller
    {
        [HttpGet]
        public ActionResult ListaTarea(int ActividadID)
        {
            ActividadID = 4;
            List<entTarea> lista = logTarea.Instancia.ListarTarea(ActividadID);
            ViewBag.listaTarea = lista;
            return View(lista);
        }

        [HttpGet]
        public ActionResult NuevaTarea()
        {
            return View();
        }

        [HttpPost]
        public ActionResult NuevaTarea(entTarea tp)
        {
            try
            {
                Boolean inserta = logTarea.Instancia.InsertarTarea(tp);

                if (inserta)
                {
                    return RedirectToAction("ListaTarea");
                }
                else
                {
                    return View(tp);
                }
            }
            catch (ApplicationException ex)
            {
                return RedirectToAction("NuevaTarea", new { msjException = ex.Message });
            }

        }

        [HttpGet]
        public ActionResult EditaTarea(int tareaID, int actividadID)
        {
            entTarea a = logTarea.Instancia.ObtenerTarea(tareaID, actividadID);
            return View(a);
        }

        [HttpPost]
        public ActionResult EditaTarea(entTarea tp)
        {
            try
            {
                Boolean edita = logTarea.Instancia.EditaTarea(tp);

                if (edita)
                {
                    return RedirectToAction("ListaTarea");
                }
                else
                {
                    return View();
                }
            }
            catch (ApplicationException ex)
            {
                return RedirectToAction("EditaTarea", new { msjException = ex.Message });
            }
        }

        [HttpGet]
        public ActionResult EliminaTarea(int tareaID, int actividadID)
        {
            try
            {
                Boolean elimina = logTarea.Instancia.EliminaTarea(tareaID,actividadID);
                return RedirectToAction("ListaTarea");
            }
            catch (ApplicationException ex)
            {
                return RedirectToAction("ListaTarea", new { msjException = ex.Message });
            }
        }
    }
}

ProyectoDiarsProgramacionDeObras/ProyectoDiarsProgramacionDeObras/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("EscalaSAC", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Obras", "ListaObra", "Obra")</li>
                    
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Programar Obras
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Programar Actividades", "ListaPrograma", "Programa")</li>
                            <li>@Html.ActionLink("Programar Tarea", "ListaTarea", "Tarea")</li>
                        </ul>
                    </li>

                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Reportes
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Reportar obra</a></li>
                            <li><a href="#">Reportar actividad</a></li>
                        </ul>
                    </li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Escala Constructores S.A.C.</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>